"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+49tggs97wvyc8y74_5q5i70d834v#0b^lcdvx81yjv9wmw_k*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',                          # ← deve vir ANTES do django.contrib.admin
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'contatos',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'maxpesa.tecnologia@gmail.com'
EMAIL_HOST_PASSWORD = 'kazv ulkb kuzx ulpt'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


CORS_ALLOW_ALL_ORIGINS = True


# ================================================================
#  UNFOLD — Tema SARENS (preto e dourado)
# ================================================================
UNFOLD = {
    "SITE_TITLE":  "SARENS",
    "SITE_HEADER": "SARENS — Painel Operacional",
    "SITE_URL":    "/",
    "SITE_SYMBOL": "settings",

    "COLORS": {
        "primary": {
            "50":  "250 243 224",
            "100": "245 231 179",
            "200": "240 214 128",
            "300": "232 193 85",
            "400": "220 172 60",
            "500": "200 168 75",
            "600": "180 148 55",
            "700": "150 120 40",
            "800": "110 88 28",
            "900": "70 55 15",
            "950": "40 30 5",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Comercial",
                "separator": True,
                "items": [
                    {
                        "title": "Leads",
                        "icon":  "inbox",
                        "link":  "/admin/contatos/lead/",
                    },
                    {
                        "title": "Operações",
                        "icon":  "engineering",
                        "link":  "/admin/contatos/operacao/",
                    },
                    {
                        "title": "Financeiro",
                        "icon":  "payments",
                        "link":  "/admin/contatos/financeiro/",
                    },
                ],
            },
            {
                "title": "Frota",
                "separator": True,
                "items": [
                    {
                        "title": "Equipamentos",
                        "icon":  "construction",
                        "link":  "/admin/contatos/equipamento/",
                    },
                ],
            },
            {
                "title": "Equipe",
                "separator": True,
                "items": [
                    {
                        "title": "Analistas",
                        "icon":  "group",
                        "link":  "/admin/contatos/perfilanalista/",
                    },
                    {
                        "title": "Usuários",
                        "icon":  "manage_accounts",
                        "link":  "/admin/auth/user/",
                    },
                ],
            },
        ],
    },
}