# Generated by Django 6.0.2 on 2026-03-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
