# Generated by Django 6.0.2 on 2026-03-03 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do equipamento')),
                ('categoria', models.CharField(choices=[('guindastes', 'Guindastes'), ('munck', 'Caminhões Munck'), ('empilhadeira', 'Empilhadeiras'), ('linha-amarela', 'Linha Amarela')], max_length=30, verbose_name='Categoria')),
                ('capacidade', models.CharField(blank=True, max_length=60, verbose_name='Especificação técnica')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo na frota')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.DecimalField(decimal_places=2, help_text='Valor total cobrado ao cliente', max_digits=12, verbose_name='Receita (R$)')),
                ('despesa', models.DecimalField(decimal_places=2, default=0, help_text='Custo operacional total', max_digits=12, verbose_name='Despesa (R$)')),
                ('status_pgto', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcialmente pago'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='Status do pagamento')),
                ('data_pgto', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações financeiras')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiro',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('categoria', models.CharField(choices=[('guindastes', 'Guindastes'), ('munck', 'Caminhões Munck'), ('empilhadeira', 'Empilhadeiras'), ('linha-amarela', 'Linha Amarela'), ('outro', 'Outro / Orçamento Personalizado')], default='outro', max_length=30, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, choices=[('at-100', 'Guindaste AT 100t'), ('rt-200', 'Guindaste RT 200t'), ('tre-500', 'Guindaste Treliçado 500t'), ('munck-10', 'Caminhão Munck 10t'), ('munck-20', 'Caminhão Munck 20t'), ('empilh-8', 'Empilhadeira 8t'), ('escav-30', 'Escavadeira Hidráulica 30t'), ('pa-carg', 'Pá Carregadeira'), ('outro', 'Outro / A definir')], default='outro', max_length=30, verbose_name='Subcategoria')),
                ('mensagem', models.TextField(verbose_name='Descrição da necessidade')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado / Ganho'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Analista responsável')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de término')),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('noturno', 'Noturno'), ('24h', '24h (Dia e Noite)')], default='diurno', max_length=10, verbose_name='Turno')),
                ('local_operacao', models.CharField(blank=True, max_length=300, verbose_name='Local da operação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações técnicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='contatos.equipamento', verbose_name='Equipamento')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='contatos.lead', verbose_name='Lead de origem')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAnalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('analista_jr', 'Analista Comercial Jr.'), ('analista_pl', 'Analista Comercial Pl.'), ('analista_sr', 'Analista Comercial Sr.'), ('coordenador', 'Coordenador Comercial'), ('gerente', 'Gerente Comercial')], default='analista_pl', max_length=20, verbose_name='Cargo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone / WhatsApp')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn (URL)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='analistas/', verbose_name='Foto de perfil')),
                ('bio', models.TextField(blank=True, help_text='Breve descrição da especialidade do analista', verbose_name='Bio / Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Analista',
                'verbose_name_plural': 'Perfis dos Analistas',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='operacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='contatos.operacao', verbose_name='Operação'),
        ),
    ]
