# Generated by Django 6.0.2 on 2026-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_equipamento_financeiro_lead_operacao_perfilanalista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ultimo_contato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último contato'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='despesa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesa (R$)'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='receita',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Receita (R$)'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='status_pgto',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='Status do pagamento'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_atendimento', 'Em atendimento'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='perfilanalista',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio / Especialidade'),
        ),
    ]
